# Generated by Django 4.2 on 2023-07-10 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Consulta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaSemana', models.CharField(blank=True, choices=[('SF', 'Segunda-feira'), ('TF', 'Terça-feira'), ('QAF', 'Quarta-feira'), ('QIF', 'Quinta-feira'), ('SF', 'Sexta-feira'), ('S', 'Sábado'), ('D', 'Domingo')], max_length=50, null=True)),
                ('quantidade', models.CharField(max_length=255)),
                ('alimento', models.CharField(max_length=255)),
                ('horario', models.CharField(max_length=255)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dieta', to='Consulta.consulta')),
            ],
        ),
    ]
