# Generated by Django 4.0.3 on 2023-06-05 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dieta', '0002_dieta_paciente_dieta_profissional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dieta',
            name='diaSemana',
            field=models.CharField(blank=True, choices=[('SF', 'Segunda-feira'), ('TF', 'Terça-feira'), ('QAF', 'Quarta-feira'), ('QIF', 'Quinta-feira'), ('SF', 'Sexta-feira'), ('S', 'Sábado'), ('D', 'Domingo')], max_length=50, null=True),
        ),
    ]
