# Generated by Django 4.2 on 2023-04-30 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao', models.CharField(blank=True, choices=[('Disponível', 'D'), ('Indisponível', 'I')], max_length=50, null=True)),
                ('dataHoraComeco', models.DateTimeField()),
                ('dataHoraFinal', models.DateTimeField()),
            ],
        ),
    ]
