# Generated by Django 4.2 on 2023-05-13 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Horario', '0001_initial'),
        ('Consulta', '0003_alter_consulta_paciente_alter_consulta_profissional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='dataHoraComeco',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='dataHoraFinal',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='profissional',
        ),
        migrations.RemoveField(
            model_name='consulta',
            name='situacao',
        ),
        migrations.AddField(
            model_name='consulta',
            name='horario',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='horario', to='Horario.horario'),
            preserve_default=False,
        ),
    ]
