# Generated by Django 4.2 on 2023-07-10 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Consulta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diaSemana', models.CharField(blank=True, choices=[('Segunda-feira', 'SF'), ('Terça-feira', 'TF'), ('Quarta-feira', 'QAF'), ('Quinta-feira', 'QIF'), ('Sexta-feira', 'SF'), ('Sábado', 'S'), ('Domingo', 'D')], max_length=50, null=True)),
                ('exercicio', models.CharField(max_length=255)),
                ('serie', models.CharField(max_length=255)),
                ('repeticao', models.CharField(max_length=255)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treino', to='Consulta.consulta')),
            ],
        ),
    ]
