# Generated by Django 4.2 on 2023-04-30 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('Treino', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treino',
            name='paciente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pacienteT', to='accounts.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='treino',
            name='profissional',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='professionalT', to='accounts.usuario'),
            preserve_default=False,
        ),
    ]
