# Generated by Django 4.2 on 2023-07-30 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prontuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prontuario',
            name='observacoes',
            field=models.CharField(max_length=2500),
        ),
    ]
