# Generated by Django 4.2 on 2023-04-30 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('Prontuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prontuario',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to='accounts.usuario'),
        ),
        migrations.AddField(
            model_name='prontuario',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional', to='accounts.usuario'),
        ),
    ]
