# Generated by Django 4.2 on 2023-04-30 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('Prontuario', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prontuario',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacienteP', to='accounts.usuario'),
        ),
        migrations.AlterField(
            model_name='prontuario',
            name='profissional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professionalP', to='accounts.usuario'),
        ),
    ]
