# Generated by Django 4.2 on 2023-07-10 13:59

import core.validators
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('codigoAutenticador', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('cpf', models.CharField(max_length=13, unique=True, validators=[core.validators.validate_cpf])),
                ('tipo', models.CharField(choices=[('A', 'Administrador'), ('C', 'Cliente'), ('N', 'Nutricionista'), ('EF', 'EducadorFisico')], max_length=2)),
                ('localAtendimento', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
