# Generated by Django 4.2 on 2023-05-02 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigoAutenticador',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
