# Generated by Django 4.2 on 2023-04-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_usuario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[('A', 'Administrador'), ('C', 'Cliente'), ('N', 'Nutricionista'), ('EF', 'EducadorFisico')]),
        ),
    ]
