# Generated by Django 4.2 on 2023-04-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_usuario_date_joined_remove_usuario_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('A', 'Administrador'), ('C', 'Cliente'), ('N', 'Nutricionista'), ('EF', 'EducadorFisico')], max_length=2),
        ),
    ]
