# Generated by Django 4.2 on 2023-04-30 21:12

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_usuario_cpf_alter_usuario_user_ptr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.CharField(max_length=13, unique=True, validators=[core.validators.validate_cpf]),
        ),
    ]
