# Generated by Django 4.2 on 2023-07-10 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(help_text='Insira uma data para agenda')),
                ('hora', models.TimeField(default=datetime.time(10, 0))),
                ('preenchido', models.BooleanField(default=False)),
            ],
        ),
    ]
