# Generated by Django 4.2 on 2023-05-14 00:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usuario_codigoautenticador'),
        ('Horario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='horarioComeco',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='horarioFim',
        ),
        migrations.AddField(
            model_name='horario',
            name='agenda',
            field=models.CharField(choices=[('1', '07:00 ás 08:00'), ('2', '08:00 ás 09:00'), ('3', '09:00 ás 10:00'), ('4', '10:00 ás 11:00'), ('5', '11:00 ás 12:00')], default=2, max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horario',
            name='dia',
            field=models.DateField(default=django.utils.timezone.now, help_text='Insira uma data para agenda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='horario',
            name='profissional',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='professionalH', to='accounts.usuario'),
            preserve_default=False,
        ),
    ]
