# Generated by Django 4.0.3 on 2023-06-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Horario', '0002_remove_horario_horariocomeco_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='status',
            field=models.CharField(choices=[('Vago', 'nenhuma consulta'), ('Preenchido', 'consulta')], default='Vago', max_length=20),
        ),
    ]
