# Generated by Django 4.0.3 on 2023-06-06 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Horario', '0003_horario_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='status',
            field=models.CharField(choices=[('Vago', 'Aberto para atendimento'), ('Preenchido', 'Horario preenchido')], default='Vago', max_length=20),
        ),
    ]
